web:
    image: "gitlab/gitlab-ee:latest"
    restart: always
    hostname: "localhost"
    environment:
        GITLAB_OMNIBUS_CONFIG: |
            external_url 'http://localhost:8929'
            gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
        - "8929:8929"
        - "2224:22"
    volumes:
        - "$GITLAB_HOME/config:/etc/gitlab"
        - "$GITLAB_HOME/logs:/var/log/gitlab"
        - "$GITLAB_HOME/data:/var/opt/gitlab"
