# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:14.15.3

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
services:
    - mongo:latest
    - rabbitmq:3.8.9-management-alpine
    - redis:6.0.9-alpine

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
    paths:
        - node_modules/

include:
    - template: Code-Quality.gitlab-ci.yml

code_quality:
    services: # Shut off Docker-in-Docker
    tags:
        - cq-sans-dind # Set this job to only run on our new specialized runner

stages:
    - test
# test:
#     script:
#         - npm i
#         - npm i -g pm2
#         - pm2 install typescript
#         - pm2 start pm2.deploy.json
#         - sleep 10
#         - curl http://localhost:4263/rest/v1
#         - pm2 stop all
#         - pm2 delete all

