sudo: required

language: node_js

node_js:
    - "14"

dist:
    - "bionic"

addons:
    apt:
        packages:
            - rabbitmq-server
services:
    - mongodb
    - redis-server
    - rabbitmq

script:
    - sudo npm install --no-cache
    - sudo npm i -g pm2
    - sudo pm2 install typescript
    - sudo pm2 start pm2.deploy.json
    - echo "Setup more below"
    - sleep 10
    - curl http://localhost:$PORT/rest/v1
    - sudo pm2 stop all
    - sudo pm2 delete all
