language: node_js
node_js:
    - "14"

services:
    - docker

before_install:
    - sudo docker pull rabbitmq:3.8.9-management-alpine
    - sudo docker run -d --hostname my-rabbit --name some-rabbit rabbitmq:3.8.9-management-alpine

script:
    - echo "test"
    - sudo npm install --no-cache
    - sudo npm i -g pm2
    - sudo pm2 install typescript
    - sudo pm2 start pm2.deploy.json
    - sleep 10
    - curl http://localhost:${PORT}/rest/v1
    - sudo pm2 stop all
    - sudo pm2 delete all
