language: node_js
node_js:
    - "14"

services:
    - docker

before_install:
    - sudo docker pull rabbitmq:3.8.9-management-alpine
    - sudo docker run -d --hostname my-rabbit --name some-rabbit rabbitmq:3.8.9-management-alpine

install:
    - npm install --no-cache
    - npm i -g pm2
    - pm2 install typescript
    - pm2 start pm2.deploy.json
    - pm2 logs

script:
    - echo "test"
    - sleep 10
    - curl http://localhost:4263/rest/v1
    - sudo pm2 stop all
    - sudo pm2 delete all
