FROM node:18

WORKDIR /usr/src/app

COPY package*.json ./

# RUN apk add --no-cache make gcc g++ python

COPY . .

RUN npm install pm2 -g

RUN npm install --no-cache


EXPOSE 8018

CMD ["pm2-runtime", "pm2.deploy.json"]
