version: 2.1

jobs:
    build:
        docker:
            - image: circleci/node:14.15.3
            - image: circleci/mongo:4.4
            - image: circleci/rabbitmq:3.8.9
            - image: circleci/redis:6.0.8
        steps:
            - checkout
            - run:
                  name: Setup PORT => .ENV
                  command: |
                      echo 'export NODE_ENV="production"' >> $NODE_ENV
                      echo 'export RABBIT_URL="amqp://localhost"' >> $RABBIT_URL
                      echo 'export REDIS_URL="redis://127.0.0.1:6379/4"' >> $REDIS_URL
                      echo 'export DB_URL="mongodb://localhost:27017/mydb"' >> $DB_URL
            - run:
                  name: "What branch am I on?"
                  command: echo ${CIRCLE_BRANCH}
