version: 2.1

jobs:
    build:
        docker:
            - image: circleci/node:14.15.3
            - image: mongo:latest
            - image: rabbitmq:3.8.9-management-alpine
            - image: redis:6.0.9-alpine
        steps:
            - checkout
            - run: echo "docker"
    test:
        docker:
            - image: circleci/node:14.15.3
            - image: mongo:latest
            - image: rabbitmq:3.8.9-management-alpine
            - image: redis:6.0.9-alpine
        steps:
            - checkout
            - run:
                  name: "What branch am I on?"
                  command: echo ${CIRCLE_BRANCH}
            - run:
                  name: npm install
                  command: sudo npm install --no-cache
            - run:
                  name: sudo npm i -g concurrently nodemon ts-node
                  command: sudo npm i -g concurrently nodemon ts-node
            - run:
                  name: sleep 30s
                  command: sleep 30
            - run:
                  name: npm run dev
                  command: sudo npm run dev
            - run:
                  name: CURL
                  command: curl http://localhost:8018/rest/v1

workflows:
    version: 2.1
    build_and_test:
        jobs:
            - build
            - test:
                  requires:
                      - build
                  filters:
                      branches:
                          only: develop
