version: "2"

services:
    mongodb-primary:
        image: "bitnami/mongodb:4.2"
        user: root
        volumes:
            - ./mongodb-persistence/bitnami:/bitnami
        networks:
            - parse_network
        environment:
            - MONGODB_REPLICA_SET_MODE=primary
            - MONGODB_REPLICA_SET_KEY=123456789
            - MONGODB_ROOT_USERNAME=root2020
            - MONGODB_ROOT_PASSWORD=root2020
            - MONGODB_USERNAME=root2021
            - MONGODB_PASSWORD=root2021
            - MONGODB_DATABASE=admin
        ports:
            - 27017:27017

    mongodb-secondary:
        image: "bitnami/mongodb:4.2"
        depends_on:
            - mongodb-primary
        environment:
            - MONGODB_REPLICA_SET_MODE=secondary
            - MONGODB_REPLICA_SET_KEY=123456789
            - MONGODB_PRIMARY_HOST=mongodb-primary
            - MONGODB_PRIMARY_PORT_NUMBER=27017
            - MONGODB_PRIMARY_ROOT_USERNAME=root2020
            - MONGODB_PRIMARY_ROOT_PASSWORD=root2020
        networks:
            - parse_network
        ports:
            - 27027:27017

    mongodb-arbiter:
        image: "bitnami/mongodb:4.2"
        depends_on:
            - mongodb-primary
        environment:
            - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
            - MONGODB_REPLICA_SET_MODE=arbiter
            - MONGODB_PRIMARY_HOST=mongodb-primary
            - MONGODB_PRIMARY_PORT_NUMBER=27017
            - MONGODB_PRIMARY_ROOT_PASSWORD=root2020
            - MONGODB_REPLICA_SET_KEY=123456789
        networks:
            - parse_network
        ports:
            - 27037:27017

networks:
    parse_network:
        driver: bridge
        ipam:
            driver: default
volumes:
    mongodb_master_data:
        driver: local
